switch_language:
    pattern: /switchLanguage/{language}
    defaults: {_controller: BloginyBundle:Utils:switchLanguage}




blog_posts_list:
    pattern: /blog_post/list/{from}
    defaults: {_controller: BloginyBundle:BlogPost:list, from: 'none'}

blog_post_details:
    pattern: /blog_post/details/{slug}
    defaults: {_controller: BloginyBundle:BlogPost:details}

blog_post_search:
    pattern: /blog_post/search/
    defaults: {_controller: BloginyBundle:BlogPost:search}

blog_post_search_list:
    pattern: /blog/search_list/{filter}/{page}
    defaults: {_controller: BloginyBundle:BlogPost:searchPosts, page: 1}




blogs_list:
    pattern: /blog/list/{location}/{language}/{page}
    defaults: {_controller: BloginyBundle:Blog:list, location: 'all', language: 'all', page: 1}

blog_propose:
    pattern: /blog/propose
    defaults: {_controller: BloginyBundle:Blog:propose}

blog_proposed:
    pattern: /blog/proposed/{slug}
    defaults: {_controller: BloginyBundle:Blog:proposed}

blog_show:
    pattern: /blog/show/{slug}
    defaults: {_controller: BloginyBundle:Blog:show}

blog_thumbnail:
    pattern: /blog/thumbnail/{slug}
    defaults: {_controller: BloginyBundle:Blog:thumbnail}

blog_posts:
    pattern: /blog/posts/{slug}/{from}
    defaults: {_controller: BloginyBundle:Blog:posts, from: 'none'}

blog_google_ranking:
    pattern: /blog/google/{slug}
    defaults: {_controller: BloginyBundle:Blog:googleRanking}

blog_alexa_ranking:
    pattern: /blog/alexa/{slug}
    defaults: {_controller: BloginyBundle:Blog:alexaRanking}

blog_search:
    pattern: /blog/search/
    defaults: {_controller: BloginyBundle:Blog:search}

blog_search_list:
    pattern: /blog/search_list/{filter}/{page}
    defaults: {_controller: BloginyBundle:Blog:searchBlogs, page: 1}

feed_index:
    pattern: /feed/
    defaults: {_controller: BloginyBundle:Feed:blogPosts, _format: rss}

feed_blog_posts:
    pattern: /feed/blog_post/
    defaults: {_controller: BloginyBundle:Feed:blogPosts, _format: rss}

feed_top_blogs:
    pattern: /feed/blog/{location}/{language}
    defaults: {_controller: BloginyBundle:Feed:topBlogs, location: 'all', language: 'all', _format: rss}

