Rizeway\BloginyBundle\Entity\Blog:

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: url

    properties:
        title:
            - NotBlank:
                message : 'The title should not be blank'
            - Length:
                min: 3
                minMessage : 'The title is too short (At least 3 characters)'
                max: 255
                maxMessage : 'The title is too long (255 characters max)'

        description:
            - NotBlank:
                message : 'The description should not be blank'

        url:
            - NotBlank:
                message : 'The url should not be blank'
            - Url:
                message : 'The url is invalid'

        feed_url:
            - NotBlank:
                message : 'The Feed url should not be blank'
            - Url:
                message : 'The Feed url is invalid'