security:
    providers:
        in_memory:
            memory:
                users:

    firewalls:
        main:
            pattern:    ^/
            anonymous: true

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }