#services
services:
    security.encoder.md5encoder:
        class: Rizeway\UserBundle\Lib\Encoder\Md5Encoder

#security
security:
  
    providers:
        main:
            entity: { class: UserBundle:User }

    encoders:
        Rizeway\UserBundle\Entity\User:
           id: security.encoder.md5encoder

    firewalls:
        main:
            pattern:    ^/
            form-login:
                default_target_path: /user/dashboard
            logout: { target: /logged_out}
            anonymous: true
            remember_me:
              key:      mySecretForBloginy2308100
              lifetime: 3600
              path:     /

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN_USER }
        - { path: ^/user/, role: ROLE_REGISTRED_USER }
        - { path: ^/post/vote/, role: ROLE_REGISTRED_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
#parameters
parameters:
    user.activation.max_tries: 10