Rizeway\UserBundle\Entity\User:
    constraints:
        - Rizeway\ExtraFrameworkBundle\Validator\Constraints\Unique:
             property: username
        - Rizeway\ExtraFrameworkBundle\Validator\Constraints\Unique:
             property: email

    properties:
        username:
            - NotBlank:
                message : 'The usename should not be blank'
            - MinLength:
                limit: 4
                message : 'The username is too short (At least 4 characters)'
            - MaxLength:
                limit: 20
                message : 'The username is too long (20 characters max)'
            - Regex:
                pattern: /^[A-Za-z](?=[A-Za-z0-9_.]{3,19}$)[a-zA-Z0-9_]*$/
                message: 'The username shoud contain only alphanumerical characters and start with a letter'

        password:
            - NotBlank:
                message : 'The password should not be blank'
            - MinLength:
                limit: 6
                message : 'The password is too short (At least 6 characters)'
            - MaxLength:
                limit: 32
                message : 'The password is too long (32 characters max)'
        email:
            - NotBlank:
                message : 'The email should not be blank'
            - MaxLength:
                limit: 100
                message : 'The password is too long (100 characters max)'
            - Email:
                message : 'The email is invalid'
        web_site:
            - Url:
                message : 'The web site is invalid'
        twitter:
            - Url:
                message : 'The web site is invalid'
        facebook:
            - Url:
                message : 'The web site is invalid'

Rizeway\UserBundle\Model\Registration:
    properties:
        user:
            - Valid: ~
        termsAccepted:
            - AssertTrue:
                message: 'Please accept the terms and conditions'


Rizeway\UserBundle\Lib\Utils\Avatar:
    properties:
        file:
          - File: { maxSize: 128k, mimeTypes: [image/jpeg, image/png, image/gif] }